name: Deploy

on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: reggionick/s3-deploy@v4
      with:
        folder: ./
        bucket: ${{ secrets.AWS_BUCKET_NAME }}
        bucket-region: ${{ secrets.AWS_BUCKET_REGION }}
        private: true
        delete-removed: true